{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import flask\n",
    "from flask import Flask,render_template, flash, request, url_for,redirect, session\n",
    "import re\n",
    "import os\n",
    "import tensorflow as tf\n",
    "from tensorflow.keras.preprocessing import sequence\n",
    "from tensorflow.keras.models import load_model\n",
    "from skimage import io\n",
    "from forms import RegistrationForm, LoginForm\n",
    "from flask_uploads import UploadSet, configure_uploads, IMAGES"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "app = Flask(__name__)\n",
    "\n",
    "photos = UploadSet('photos', IMAGES)\n",
    "\n",
    "app.config['SECRET_KEY']='a7266cdf29030f092c955d59f1889390'\n",
    "app.config['UPLOADED_PHOTOS_DEST'] = 'C:/Users/kumar/Code/FacialEmotionRecognition'\n",
    "\n",
    "configure_uploads(app,photos)\n",
    "\n",
    "\n",
    "#load pretrained keras models\n",
    "model =  load_model('facial_sentiment_trained_32000.h5')\n",
    "\n",
    "\n",
    "@app.route('/home', methods=['GET', 'POST'])\n",
    "@app.route('/',methods=['GET', 'POST'])\n",
    "def home():\n",
    "    return render_template(\"home.html\")\n",
    "\n",
    "@app.route('/contact',methods=['GET', 'POST'])\n",
    "def contact():\n",
    "    return render_template('contact.html', title='contact')\n",
    "\n",
    "@app.route('/about',methods=['GET', 'POST'])\n",
    "def about():\n",
    "    return render_template('about.html', title='about')\n",
    "\n",
    "\n",
    "@app.route(\"/register\",methods=['GET', 'POST'])\n",
    "def register():\n",
    "    form = RegistrationForm()\n",
    "    if form.validate_on_submit():\n",
    "        flash('Account created for {form.username.data}!')\n",
    "    return render_template(\"register.html\", title='Register', form = form)\n",
    "\n",
    "@app.route(\"/login\", methods =[\"GET\", \"POST\"])\n",
    "def login():\n",
    "    form = LoginForm()\n",
    "    if form.validate_on_submit():\n",
    "        if form.email.data == 'admin@blog.com' and form.password.data == 'password':\n",
    "            flash('you have been logged in!', 'success')\n",
    "            return redirect(url_for('home'))\n",
    "        else:\n",
    "            flash('login Unsuccessful. check username and password', 'danger')\n",
    "\n",
    "    return render_template(\"login.html\", title='Login', form= form)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: This is a development server. Do not use it in a production deployment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [08/Jul/2020 15:49:21] \"\u001b[37mPOST /upload HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-07-08 15:50:54,879] ERROR in app: Exception on /upload [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-3-77e79f5628a1>\", line 5, in upload\n",
      "    img = io.imread(file_name, as_gray=True)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\skimage\\io\\_io.py\", line 48, in imread\n",
      "    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\skimage\\io\\manage_plugins.py\", line 209, in call_plugin\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\skimage\\io\\_plugins\\imageio_plugin.py\", line 10, in imread\n",
      "    return np.asarray(imageio_imread(*args, **kwargs))\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\imageio\\core\\functions.py\", line 265, in imread\n",
      "    reader = read(uri, format, \"i\", **kwargs)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\imageio\\core\\functions.py\", line 172, in get_reader\n",
      "    request = Request(uri, \"r\" + mode, **kwargs)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\imageio\\core\\request.py\", line 121, in __init__\n",
      "    self._parse_uri(uri)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\imageio\\core\\request.py\", line 257, in _parse_uri\n",
      "    raise FileNotFoundError(\"No such file: '%s'\" % fn)\n",
      "FileNotFoundError: No such file: 'C:\\Users\\kumar\\Code\\Facial  Emotion Recognition\\download_1_1_1.jpg'\n",
      "127.0.0.1 - - [08/Jul/2020 15:50:55] \"\u001b[1m\u001b[35mPOST /upload HTTP/1.1\u001b[0m\" 500 -\n",
      "[2020-07-08 15:51:24,631] ERROR in app: Exception on /upload [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-3-77e79f5628a1>\", line 5, in upload\n",
      "    img = io.imread(file_name, as_gray=True)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\skimage\\io\\_io.py\", line 48, in imread\n",
      "    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\skimage\\io\\manage_plugins.py\", line 209, in call_plugin\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\skimage\\io\\_plugins\\imageio_plugin.py\", line 10, in imread\n",
      "    return np.asarray(imageio_imread(*args, **kwargs))\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\imageio\\core\\functions.py\", line 265, in imread\n",
      "    reader = read(uri, format, \"i\", **kwargs)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\imageio\\core\\functions.py\", line 172, in get_reader\n",
      "    request = Request(uri, \"r\" + mode, **kwargs)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\imageio\\core\\request.py\", line 121, in __init__\n",
      "    self._parse_uri(uri)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\imageio\\core\\request.py\", line 257, in _parse_uri\n",
      "    raise FileNotFoundError(\"No such file: '%s'\" % fn)\n",
      "FileNotFoundError: No such file: 'C:\\Users\\kumar\\Code\\Facial  Emotion Recognition\\download_1_1_2.jpg'\n",
      "127.0.0.1 - - [08/Jul/2020 15:51:24] \"\u001b[1m\u001b[35mPOST /upload HTTP/1.1\u001b[0m\" 500 -\n",
      "[2020-07-08 15:51:29,571] ERROR in app: Exception on /upload [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-3-77e79f5628a1>\", line 5, in upload\n",
      "    img = io.imread(file_name, as_gray=True)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\skimage\\io\\_io.py\", line 48, in imread\n",
      "    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\skimage\\io\\manage_plugins.py\", line 209, in call_plugin\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\skimage\\io\\_plugins\\imageio_plugin.py\", line 10, in imread\n",
      "    return np.asarray(imageio_imread(*args, **kwargs))\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\imageio\\core\\functions.py\", line 265, in imread\n",
      "    reader = read(uri, format, \"i\", **kwargs)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\imageio\\core\\functions.py\", line 172, in get_reader\n",
      "    request = Request(uri, \"r\" + mode, **kwargs)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\imageio\\core\\request.py\", line 121, in __init__\n",
      "    self._parse_uri(uri)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\imageio\\core\\request.py\", line 257, in _parse_uri\n",
      "    raise FileNotFoundError(\"No such file: '%s'\" % fn)\n",
      "FileNotFoundError: No such file: 'C:\\Users\\kumar\\Code\\Facial  Emotion Recognition\\download_1_1_3.jpg'\n",
      "127.0.0.1 - - [08/Jul/2020 15:51:29] \"\u001b[1m\u001b[35mPOST /upload HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [08/Jul/2020 15:51:35] \"\u001b[37mGET / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2020-07-08 15:51:42,302] ERROR in app: Exception on /upload [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-3-77e79f5628a1>\", line 5, in upload\n",
      "    img = io.imread(file_name, as_gray=True)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\skimage\\io\\_io.py\", line 48, in imread\n",
      "    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\skimage\\io\\manage_plugins.py\", line 209, in call_plugin\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\skimage\\io\\_plugins\\imageio_plugin.py\", line 10, in imread\n",
      "    return np.asarray(imageio_imread(*args, **kwargs))\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\imageio\\core\\functions.py\", line 265, in imread\n",
      "    reader = read(uri, format, \"i\", **kwargs)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\imageio\\core\\functions.py\", line 172, in get_reader\n",
      "    request = Request(uri, \"r\" + mode, **kwargs)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\imageio\\core\\request.py\", line 121, in __init__\n",
      "    self._parse_uri(uri)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\imageio\\core\\request.py\", line 257, in _parse_uri\n",
      "    raise FileNotFoundError(\"No such file: '%s'\" % fn)\n",
      "FileNotFoundError: No such file: 'C:\\Users\\kumar\\Code\\Facial  Emotion Recognition\\download_1_1_4.jpg'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [08/Jul/2020 15:51:42] \"\u001b[1m\u001b[35mPOST /upload HTTP/1.1\u001b[0m\" 500 -\n",
      "[2020-07-08 15:51:56,013] ERROR in app: Exception on /upload [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-3-77e79f5628a1>\", line 5, in upload\n",
      "    img = io.imread(file_name, as_gray=True)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\skimage\\io\\_io.py\", line 48, in imread\n",
      "    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\skimage\\io\\manage_plugins.py\", line 209, in call_plugin\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\skimage\\io\\_plugins\\imageio_plugin.py\", line 10, in imread\n",
      "    return np.asarray(imageio_imread(*args, **kwargs))\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\imageio\\core\\functions.py\", line 265, in imread\n",
      "    reader = read(uri, format, \"i\", **kwargs)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\imageio\\core\\functions.py\", line 172, in get_reader\n",
      "    request = Request(uri, \"r\" + mode, **kwargs)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\imageio\\core\\request.py\", line 121, in __init__\n",
      "    self._parse_uri(uri)\n",
      "  File \"C:\\Users\\kumar\\.conda\\envs\\Navi\\lib\\site-packages\\imageio\\core\\request.py\", line 257, in _parse_uri\n",
      "    raise FileNotFoundError(\"No such file: '%s'\" % fn)\n",
      "FileNotFoundError: No such file: 'C:\\Users\\kumar\\Code\\Facial  Emotion Recognition\\girls.jpg'\n",
      "127.0.0.1 - - [08/Jul/2020 15:51:56] \"\u001b[1m\u001b[35mPOST /upload HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    }
   ],
   "source": [
    "\n",
    "@app.route('/upload', methods= ['POST', 'GET'])\n",
    "def upload():\n",
    "    if request.method==\"POST\":\n",
    "        file_name = photos.save(request.files['photo'])\n",
    "        img = io.imread(file_name, as_gray=True)\n",
    "        \n",
    "        array = tf.keras.preprocessing.image.img_to_array(img)\n",
    "        image = tf.keras.preprocessing.image.array_to_img(array)\n",
    "        im1 = image.resize((48,48))\n",
    "        final_array = tf.keras.preprocessing.image.img_to_array(im1)\n",
    "        final_final_array = (np.array(final_array)).reshape((1,) + final_array.shape)\n",
    "        answer = model.predict_classes(final_final_array)\n",
    "        mapp = {\n",
    "            0 : 'Angry', 1:'Disgust', 2: 'Fear', 3: 'Happy', 4: 'Sad', 5 :'Suprise', 6: 'Neutral' \n",
    "        }\n",
    "        final_answer = mapp[answer[0]]\n",
    "    return render_template('home.html',sentiment=final_answer)\n",
    "if __name__ == \"__main__\":\n",
    "    app.run()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
